### ISSUE TITLE
ESMF doesn't build with netcdf-c 4.9.3

### ISSUE THREAD

**Issue by thebaptiste** [esmf-org/esmf#353]
Trying to build ESMF 8.8.0 against netcdf-c 4.9.3, I have this error : 
```
/src/layers/layer1_scientific/0050_esmf/build/esmf-8.8.0/src/Infrastructure/IO/PIO/ParallelIO/src/clib/pio_nc.c: In function 'PIOc_def_var_fill':
/src/layers/layer1_scientific/0050_esmf/build/esmf-8.8.0/src/Infrastructure/IO/PIO/ParallelIO/src/clib/pio_nc.c:2433:56: error: '_FillValue' undeclared (first use in this function); did you mean 'NC_FillValue'?
 2433 |                     ierr = nc_put_att(file->fh, varid, _FillValue, xtype, 1, fill_valuep);
      |                                                        ^~~~~~~~~~
      |                                                        NC_FillValue
```
Looking at [netcdf-c release notes](https://github.com/Unidata/netcdf-c/blob/main/RELEASE_NOTES.md), I found this for 4.9.3 rc 2 : 
```
Release Candidate 2 - December 6, 2024

    Note: To avoid a conflict between _FillValue and libc++18, we have introduced a new option, --enable-legacy-macros for autotools and NETCDF_ENABLE_LEGACY_MACROS for cmake. These are turned on by default currently but will be turned off eventually. Developers are encouraged to move away from the FillValue macro and replace it with the new NC_FillValue macro. See https://github.com/Unidata/netcdf-c/issues/2858 for more information.
```
So I think you should replace `_FillValue` by `NC_FillValue` in ESMF code (as suggested in the error message).
May be adding `#define NETCDF_ENABLE_LEGACY_MACROS` before including `netcdf.h` would do the job too.

Regards

**Comment by billsacks** [comment]
Thank you for making us aware of this issue. Based on the error you're getting and the discussion in https://github.com/Unidata/netcdf-c/issues/3017, it looks like this is a broader issue with compatibility of PIO with the latest NetCDF version; as such, I think this will need to be addressed in either NetCDF or PIO. I'm going to close this here for now, but we can revisit it if it seems like something needs to be done in ESMF beyond the PIO changes.

**Comment by thebaptiste** [comment]
It seems to be fixed in release 2.6.5 of PIO. But the [PIO code included in ESMF](https://github.com/esmf-org/esmf/tree/develop/src/Infrastructure/IO/PIO/ParallelIO) two years ago is corresponding to 2.6.2 release.
So I tjink you should : 
- upgrade the included PIO code to 2.6.5
- or (easier), add the lines below in `pio.h` as done in PIO 2.6.5 release : 
```
#ifndef NC_FillValue
#define NC_FillValue _FillValue
#endif
```

**Comment by thebaptiste** [comment]
I think this issue should not be closed...

**Comment by billsacks** [comment]
Thanks for pointing this out. Given that this has been fixed in PIO, I'll reopen as you suggest and use this to track our update to the latest PIO.

**Comment by thebaptiste** [comment]
Thanks for the fix. Do you plan a new release including it soon ?

**Comment by thebaptiste** [comment]
May be you could release ESMF 8.8.1 with this fix (there will probably other users encountering this problem by this summer), but it's not a problem for me, I can wait : 
I patched netcdf 4.9.3 (which I'm building too from sources) by adding `#define NETCDF_ENABLE_LEGACY_MACROS` at the top of `netcdf.h`

**Comment by billsacks** [comment]
@Plantain thank you for pointing this out. We are in discussion about whether to do a patch release, which will depend in part on our timeline for the 8.9 release. In the meantime, if you are able to use an ESMF development version in your workflow, this has been fixed since tag v8.9.0b03 (the most recent development tag is v8.9.0b05). Alternatively, if you prefer to stick with something close to the release, I can work with you to put the necessary patches on top of the 8.8.0 release. Let me know if you would like support with this.

**Comment by billsacks** [comment]
Another option is to build PIO separately, using the latest PIO release (which fixes this issue), and then point to this pre-built PIO by setting `ESMF_PIO=external`, along with setting `ESMF_PIO_INCLUDE` and `ESMF_PIO_LIBPATH`. (I can also support you with that approach if you are having trouble getting that to work.)

**Comment by billsacks** [comment]
Thank you: we appreciate your sharing your thoughts on this.

**Comment by thebaptiste** [comment]
Is it fixed in the patch release 8.8.1 ?

**Comment by billsacks** [comment]
Yes, this is fixed in the 8.8.1 patch release, which is coming out today.

This fix was the main motivation for that patch release. Thank you to everyone who provided thoughts on this!
